### ISSUE TITLE
Need to Upgrade Gradle, Fix Bugs, Optimize Code, and Add Documentation

### ISSUE THREAD

**Issue by Jumman04** [sarowarhosen03/shttpApi#1]
This issue is created to address the following tasks:

1. **Upgrade Gradle:** Update the Gradle version to the latest for improved performance and compatibility.

2. **Fix Bugs:** Identify and resolve any existing bugs to enhance the stability and reliability of the project.

3. **Optimize Code:** Perform code optimizations to improve efficiency, readability, and maintainability.

4. **Add Documentation:** Enhance project documentation to provide comprehensive information for developers and contributors.

**Comment by Jumman04** [comment]
### @sarowarhosen03  This issue has been resolved, and the [pull request](https://github.com/sarowarhosen03/shttpApi/pull/2) has been submitted. Kindly review and approve the [pull request](https://github.com/sarowarhosen03/shttpApi/pull/2).

**Comment by sarowarhosen03** [comment]
Thanks for your valuable contribution
