### ISSUE TITLE
Add Content to Jitpack Section

### ISSUE THREAD

**Issue by Jumman04** [sarowarhosen03/shttpApi#3]
The Jitpack section has been created, but there's no content available.
![image](https://github.com/sarowarhosen03/shttpApi/assets/113237846/d6768dd1-4b46-4b02-bef4-90abd92c3336)

**Comment by sarowarhosen03** [comment]
appreciate your contribution 💖

**Comment by Jumman04** [comment]
### @sarowarhosen03  This issue has been resolved, and the [pull request](https://github.com/sarowarhosen03/shttpApi/pull/4) has been submitted. Kindly review and approve the [pull request](https://github.com/sarowarhosen03/shttpApi/pull/4).
